[redis]
url = "redis://192.168.0.34:6379"

[llm]
url = "http://192.168.1.83:11434/api/generate"
model = "llama3"

[init-tasks]
task1 = {name = "Self Health Check: check then task assigned, make a bulletpoint list and start working on it", action = "check_status"} 
task2 = {name = "Read from Redis", action = "display_redis_data"} 
task3 = {name = "Start LLM interaction", action = "start_llm_communications"} 
task4 = {name = "Log Analysis", action = "comment_last_logs"} 
task5 = {name = "Self analysys and new tasks", action = "take_improvement_actions"} 
task6 = {name = "Write a detailed report of concepts and behaviors learned so far", action = "write_detailed_report"} 
